var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //inter-state borders
		'lakesColor':'#ACE9FC', // lakes color
		'namesColor':'#919191', //color of short names
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'Andaman and Nicobar Islands', //state hover content
		'url':'', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#EBECED', //state's color when page loads
		'overColor':'#FFEE88', //state's color when mouse hover
		'downColor':'#FFEE88',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'hover': 'Andhra Pradesh',
		'url':'http://appeti.in/shop/node/110043/andhra-pradesh',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_3':{
		'hover': 'Arunachal Pradesh',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		'hover': 'Assam',
		'url':'http://appeti.in/shop/node/1100543/assam',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_5':{
		'hover': 'Bihar',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		'hover': 'Chandigarh',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_7':{
		'hover': 'Chhattisgarh',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_8':{
		'hover': 'Daman and Diu',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_9':{
		'hover': 'Delhi',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_10':{
		'hover': 'Dadra and Nagar Haveli',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_11':{
		'hover': 'Goa',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		'hover': 'Gujarat',
		'url':'http://appeti.in/shop/node/110011/gujarat',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		'hover': 'Himachal Pradesh',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_14':{
		'hover': 'Haryana',
		'url':'http://appeti.in/shop/node/110053/haryana',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_15':{
		'hover': 'Jharkhand',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_16':{
		'hover': 'Jammu and Kashmir',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_17':{
		'hover': 'Karnataka',
		'url':'http://appeti.in/shop/node/110042/karnataka',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_18':{
		'hover': 'Kerela',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_19':{
		'hover': 'Lakshadweep',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_20':{
		'hover': 'Maharashtra',
		'url':'http://appeti.in/shop/node/110012/maharashtra',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_21':{
		'hover': 'Meghalaya',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_22':{
		'hover': 'Manipur',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_23':{
		'hover': 'Madhya Pradesh',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_24':{
		'hover': 'Mizoram',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_25':{
		'hover': 'Nagaland',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_26':{
		'hover': 'Odisha',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_27':{
		'hover': 'Punjab',
		'url':'http://appeti.in/shop/node/110054/punjab',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_28':{
		'hover': 'Puducherry',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_29':{
		'hover': 'Rajasthan',
		'url':'http://appeti.in/shop/node/110013/rajasthan',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_30':{
		'hover': 'Sikkim',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_31':{
		'hover': 'Telengana',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_32':{
		'hover': 'Tamil Nadu',
		'url':'http://appeti.in/shop/node/110041/tamil-nadu',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_33':{
		'hover': 'Tripura',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_34':{
		'hover': 'Uttar Pradesh',
		'url':'http://appeti.in/shop/node/110051/uttar-pradesh',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_35':{
		'hover': 'Uttarakhand',
		'url':'',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	},
	'map_36':{
		'hover': 'West Bengal',
		'url':'http://appeti.in/shop/node/110021/west-bengal',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':true,
	}
}
